version: '3'
services:
  mongodb:
    build:
      context: mongo
      dockerfile: Dockerfile
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: --smallfiles
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: asaplog
    #   MONGO_INITDB_ROOT_PASSWORD: 111222
    #   MONGO_INITDB_DATABASE: crud
    #   MONGODB_DATA_DIR: /data/db
    #   MONDODB_LOG_DIR: /dev/null
    
   
volumes:
  mongodbdata:
    driver: local
